apiVersion: apps/v1
kind: Deployment
metadata:
  name: $CI_PROJECT_NAME
  namespace: $K8S_NAMESPACE
spec:
  replicas: $REPLICA
  selector:
    matchLabels:
      app: $CI_PROJECT_NAME
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: $CI_PROJECT_NAME
    spec:
      containers:
        - name: $CI_PROJECT_NAME
          image: $DOCKER_IMAGE_FULL_NAME
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "${REQUEST_MEMORY}"
              cpu: "${REQUEST_CPU}"
            limits:
              memory: "${LIMIT_MEMORY}"
              cpu: "${LIMIT_CPU}"
          ports:
            - name: default-port
              containerPort: 13000
          readinessProbe:
            successThreshold: 1
            failureThreshold: 2
            tcpSocket:
              port: default-port
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 30
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            tcpSocket:
              port: default-port
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 30
          env:
            - name: ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: connection-config
                  key: ConnectionString
            - name: RabbitMqUrl
              valueFrom:
                configMapKeyRef:
                  name: rabbit-mq-config
                  key: RabbitMqUrl
            - name: KafkaBrokers
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KafkaBrokers
            - name: RabbitMqUsername
              valueFrom:
                configMapKeyRef:
                  name: rabbit-mq-config
                  key: RabbitMqUsername
            - name: RabbitMqPassword
              valueFrom:
                configMapKeyRef:
                  name: rabbit-mq-config
                  key: RabbitMqPassword
            - name: NLogConfig
              valueFrom:
                configMapKeyRef:
                  name: nlog-config
                  key: logging-only-errors-with-info
            - name: DOTNET_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: TZ
            - name: TableName
              value: Demo.Outbox
      restartPolicy: Always
